spring:
  datasource :
    url : jdbc:mysql://localhost:3306/SpringDB?useSSL=false
    username : root
    password : root

#JPA Setting
jpa:
  hibernate:
    ddl-auto : update
    dialect : org.hibernate.dialect.MySQLDialect

jpa.hibernate.ddl-auto : update